### ISSUE TITLE
Funções menos específicas para merendas aqui na lib

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/rsagrespb#1]
Queria sugerir que as funções fossem escritas menos orientadas ao caso específico da merenda. eu sugeriria que as funções todas recebessem os códigos de subfunção orçamentária, regexp e o que mais for preciso para o caso da merenda especificamente, e que as funções pudessem assim ser usadas para outros casos. a especificação da merenda em si como assunto ficaria nas nossas análises (Rmds em outros repos)

**Comment by jcnevess** [comment]
Corrigido pelo commit 140da9c
